Algoritmo "atividade01-casa"

//Klelson rodrigues-atvidade 01- slide 01- venturus
Var
correntista:caractere
agencia,conta:real

Inicio
escreval("digite o nome do correntista")
leia(correntista)
escreval("Digite o numero da agencia ")
leia(agencia)
escreval ("Digite o numero da conta")
leia(conta)
escreval(" nome do correntista ",correntista)
escreval(" numero da agencia ",agencia)
escreval(" numero da conta ",conta)


Fimalgoritmo