Algoritmo

// klelson rodrigues-atividade01-slide01-venturus
Var
// Seção de Declarações das variáveis 
n1,n2,soma,substracao,multiplicacao,divisao :real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite um numero")
leia(n1)
escreva ("digite um numero")
leia(n2)
soma <- n1+n2;
substracao <- n1 - n2;
multiplicacao <- n1 * n2;
divisao <- n1 / n2;
escreval(soma)
escreval(substracao)
escreval(multiplicacao)
escreval(divisao)
Fimalgoritmo