Algoritmo "semnome"
//klelson rodrigues-atividade08-slide 01-venturus
Var
A,B,C:real
Inicio
escreval("valor de A:")
leia(A)
escreval("valor de B:")
leia(B)
escreval("valor de C:")
leia(C)

se (A=B) então
escreval("A é igual a B")
fimse
se (A>B) então
escreval("A é maior de B")
fimse
se (A>=B) então
escreval("A é maior ou igual a B")
fimse
se (C<B) então
escreval("C é menor que B")
fimse
se (C<>B) então
escreval("C é diferente B")
fimse
Fimalgoritmo