Algoritmo "semnome"
// klelosn rodrigues- atividade02-slide01-venturus
Var
aluno:caractere
nota1,nota2,nota3,media:real

Inicio
escreval("digite o nome do aluno")
leia(aluno)
escreval ("digite a primeira nota da prova do aluno: ")
leia(nota1)
escreval ("digite a segunda nota da prova do aluno: ")
leia(nota2)
escreval ("digite a terceira nota da prova do aluno :")
leia(nota3)

media<-(nota1+nota2+nota3)/3;
escreval("aluno de nome ",aluno,", possui media",media)

Fimalgoritmo